import fs from 'node:fs/promises';import path from 'node:path';import pc from 'picocolors';import {findProjectRoot} from '../utils/find-project-root.js';import {validateReactProject,supportsTests} from '../utils/validate-project.js';import {loadConfig} from '../config/load-config.js';import {displayPath} from '../utils/paths.js';import {writePlan} from '../utils/file-writer.js';import {kebabCase} from '../utils/naming.js';import type {GenerationPlan} from '../types/generator.types.js';import type {Command} from 'commander';
export async function context(cwd?:string){const start=path.resolve(process.cwd(),cwd??'.'),root=await findProjectRoot(start),pkg=await validateReactProject(root),loaded=await loadConfig(root);if(!loaded.found)console.log(pc.yellow('No .react-scaffold.json found; using defaults. Run react-scaffold init to customize them.'));return {root,pkg,...loaded}}
export async function features(root:string,dir:string){try{return (await fs.readdir(path.join(root,dir),{withFileTypes:true})).filter(x=>x.isDirectory()).map(x=>x.name).sort()}catch{return []}}
export async function requireFeature(root:string,dir:string,feature:string,noFeaturesMessage='No features found.'):Promise<string>{const all=await features(root,dir);if(!all.length)throw new Error(noFeaturesMessage);const normalized=kebabCase(feature);if(!all.includes(normalized))throw new Error(`Feature "${feature}" not found. Existing features: ${all.join(', ')}`);return normalized}
export async function execute(label:string,plan:GenerationPlan,force=false){const result=await writePlan(plan,force);console.log(pc.green(`✔ Created ${label}`));for(const f of result.files)console.log(`  ${displayPath(plan.root,f)}`)}
export function testAllowed(pkg:Record<string,unknown>,wanted:boolean){if(wanted&&!supportsTests(pkg)){console.warn(pc.yellow('Test file skipped: install Vitest and @testing-library/react (or another recognized setup) first.'));return false}return wanted}
export function optionSupplied(command:Command,name:string):boolean{const source=command.getOptionValueSource(name);return !!source&&source!=='default'}
export function validateExclusiveOptions(command:Command,names:string[]):void{const supplied=names.filter(name=>optionSupplied(command,name));if(supplied.length>1)throw new Error(`Choose only one of ${names.map(name=>`--${name}`).join(', ')}.`)}
export function explicitBoolean(command:Command,options:Record<string,unknown>,name:string):boolean|undefined{return optionSupplied(command,name)?Boolean(options[name]):undefined}
